---
galaxy_info:
  role_name: zabbix-agent
  author: Anri Sitchinava
  description: Install and configure Zabbix Agent 2 on Ubuntu hosts
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - monitoring
    - zabbix
    - agent

dependencies:
  - role: common
