---
- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Restart unattended-upgrades
  ansible.builtin.service:
    name: unattended-upgrades
    state: restarted

- name: Restart systemd-timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted
